# Generated by Django 5.2.5 on 2026-01-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product')},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='variant',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
