# Generated by Django 5.2.1 on 2025-07-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_db', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('makanan', 'Makanan'), ('minuman', 'Minuman'), ('camilan', 'Camilan'), ('lainnya', 'Lainnya')], max_length=50),
        ),
    ]
