# Generated by Django 5.2.1 on 2025-08-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_db', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='umkm_user',
            new_name='umkm_user_id',
        ),
        migrations.AddField(
            model_name='product',
            name='umkm_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
