# Generated by Django 5.2.1 on 2025-08-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_db', '0004_rename_umkm_user_product_umkm_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='umkm_name',
        ),
    ]
