# Generated by Django 5.2.5 on 2026-02-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_db', '0004_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='midtrans_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
