# Generated by Django 5.2.5 on 2025-09-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_db', '0007_product_sold_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
