# Generated by Django 5.2.5 on 2025-09-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_db', '0008_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
