# Generated by Django 5.2.5 on 2025-09-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_db', '0010_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
